services:
  web:
    build:
      context: .  # Use the current directory for building the image
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory
    container_name: swayna-web
    restart: always  # Ensure the container restarts on failure or reboot
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=swayna.settings
    volumes:
      - .:/app  # Mount the current directory to persist database & code changes
      - static_volume:/app/staticfiles  # Persist static files
      - media_volume:/app/media
  nginx:
    image: nginx:latest
    container_name: nginx-container
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  static_volume:
  media_volume:
