# Generated by Django 5.0.6 on 2024-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="comments",
            name="user_comment",
            field=models.TextField(),
        ),
    ]
