# Generated by Django 5.0.6 on 2024-07-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_auth", "0001_initial"),
        ("shop", "0007_order_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base_auth.user_profile",
            ),
        ),
    ]
